[package]
name = "abc155"
version = "0.1.0"
authors = ["nola_suz <belljguis4@gmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]

[profile.release]
lto = true
panic = 'abort'
